"""
Script to create and manage an AWS Bedrock Knowledge Base using boto3.
This includes creating the necessary IAM roles, S3 bucket, Knowledge Base,
and syncing data as new documents are added.
Most of the boto3 code is AI-generated by Claude Sonnet 4.5 on GitHub Copilot.
Please keep all resources in us-east-1 region for compatibility.
"""

import boto3
import json
import time
import argparse
import os
from datetime import datetime
from dotenv import load_dotenv

# Import shared configuration
from config import (
    KB_CONFIGS,
    REGION,
    BUCKET_NAME,
    EMBEDDING_MODEL_ARN
)

# Load environment variables from .env file
load_dotenv()

# Tags to apply to all Knowledge Bases (loaded from .env)
KB_TAGS = {
    'Created-By': os.getenv('TAG_CREATED_BY', 'Unknown'),
    'Tech-Team': os.getenv('TAG_TECH_TEAM', 'Unknown'),
    'Center': os.getenv('TAG_CENTER', 'Unknown'),
    'Project-Code': os.getenv('TAG_PROJECT_CODE', 'Unknown'),
    'Project-Name': os.getenv('TAG_PROJECT_NAME', 'Unknown'),
    'Name': os.getenv('TAG_NAME', 'your-eval-knowledge-base')
}

# Default active KB type (can be overridden by CLI args)
ACTIVE_KB_TYPE = 'default-md'
KB_NAME = KB_CONFIGS[ACTIVE_KB_TYPE]['name']
KB_DESCRIPTION = KB_CONFIGS[ACTIVE_KB_TYPE]['description']
DATA_PREFIX = "data/"

# Initialize boto3 clients with explicit region
bedrock_agent = boto3.client('bedrock-agent', region_name=REGION)
iam = boto3.client('iam', region_name=REGION)
s3 = boto3.client('s3', region_name=REGION)
s3_vectors = boto3.client('s3vectors', region_name=REGION)
sts = boto3.client('sts', region_name=REGION)

# Get account ID
account_id = sts.get_caller_identity()['Account']

def create_s3_bucket():
    """Use existing S3 bucket for knowledge base data source"""
    print(f"Using existing S3 bucket: {BUCKET_NAME}")
    return BUCKET_NAME

def create_kb_role(vector_bucket_name):
    """Create IAM role for Bedrock Knowledge Base with S3 vector store permissions"""
    role_name = f"{KB_NAME}-role"
    
    # Trust policy for Bedrock
    trust_policy = {
        "Version": "2012-10-17",
        "Statement": [{
            "Effect": "Allow",
            "Principal": {
                "Service": "bedrock.amazonaws.com"
            },
            "Action": "sts:AssumeRole",
            "Condition": {
                "StringEquals": {
                    "aws:SourceAccount": account_id
                },
                "ArnLike": {
                    "aws:SourceArn": f"arn:aws:bedrock:{REGION}:{account_id}:knowledge-base/*"
                }
            }
        }]
    }
    
    try:
        # Create role
        try:
            response = iam.create_role(
                RoleName=role_name,
                AssumeRolePolicyDocument=json.dumps(trust_policy),
                Description=f"Role for Bedrock Knowledge Base {KB_NAME}"
            )
            role_arn = response['Role']['Arn']
            print(f"Created IAM role: {role_arn}")
        except iam.exceptions.EntityAlreadyExistsException:
            print(f"IAM role already exists: {role_name}")
            response = iam.get_role(RoleName=role_name)
            role_arn = response['Role']['Arn']
            print(f"Using existing role: {role_arn}")
        
        # Attach policies (will update if they already exist)
        # Policy for S3 data source access (read) and supplemental storage (read/write)
        s3_data_policy = {
            "Version": "2012-10-17",
            "Statement": [{
                "Effect": "Allow",
                "Action": [
                    "s3:GetObject",
                    "s3:PutObject",
                    "s3:DeleteObject",
                    "s3:ListBucket"
                ],
                "Resource": [
                    f"arn:aws:s3:::{BUCKET_NAME}",
                    f"arn:aws:s3:::{BUCKET_NAME}/*"
                ]
            }]
        }
        
        iam.put_role_policy(
            RoleName=role_name,
            PolicyName=f"{role_name}-s3-data-policy",
            PolicyDocument=json.dumps(s3_data_policy)
        )
        
        # Policy for S3 vector store access
        s3_vector_policy = {
            "Version": "2012-10-17",
            "Statement": [{
                "Effect": "Allow",
                "Action": [
                    "s3:GetObject",
                    "s3:PutObject",
                    "s3:DeleteObject",
                    "s3:ListBucket"
                ],
                "Resource": [
                    f"arn:aws:s3:::{vector_bucket_name}",
                    f"arn:aws:s3:::{vector_bucket_name}/*"
                ]
            }]
        }
        
        iam.put_role_policy(
            RoleName=role_name,
            PolicyName=f"{role_name}-s3-vector-policy",
            PolicyDocument=json.dumps(s3_vector_policy)
        )
        
        # Policy for S3 Vectors service operations
        s3_vectors_policy = {
            "Version": "2012-10-17",
            "Statement": [{
                "Effect": "Allow",
                "Action": [
                    "s3vectors:*"
                ],
                "Resource": [
                    f"arn:aws:s3vectors:{REGION}:{account_id}:bucket/{vector_bucket_name}",
                    f"arn:aws:s3vectors:{REGION}:{account_id}:bucket/{vector_bucket_name}/*"
                ]
            }]
        }
        
        iam.put_role_policy(
            RoleName=role_name,
            PolicyName=f"{role_name}-s3vectors-policy",
            PolicyDocument=json.dumps(s3_vectors_policy)
        )
        
        # Policy for Bedrock model access and Data Automation
        bedrock_policy = {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Effect": "Allow",
                    "Action": [
                        "bedrock:InvokeModel"
                    ],
                    "Resource": [
                        # Allow all foundation models (Amazon Titan, Claude, Llama, Mistral, etc.)
                        f"arn:aws:bedrock:{REGION}::foundation-model/*",
                        f"arn:aws:bedrock:*::foundation-model/*",
                        # Allow cross-region inference profiles
                        f"arn:aws:bedrock:{REGION}:{account_id}:inference-profile/*",
                        f"arn:aws:bedrock:*:{account_id}:inference-profile/*"
                    ]
                },
                {
                    "Effect": "Allow",
                    "Action": [
                        "bedrock:InvokeDataAutomationAsync",
                        "bedrock:GetDataAutomationProject",
                        "bedrock:GetDataAutomationStatus"
                    ],
                    "Resource": [
                        f"arn:aws:bedrock:*:{account_id}:data-automation-profile/*",
                        f"arn:aws:bedrock:*:{account_id}:data-automation-project/*",
                        f"arn:aws:bedrock:*:{account_id}:data-automation-invocation/*",
                        "arn:aws:bedrock:*:aws:data-automation-project/*"
                    ]
                }
            ]
        }
        
        iam.put_role_policy(
            RoleName=role_name,
            PolicyName=f"{role_name}-bedrock-policy",
            PolicyDocument=json.dumps(bedrock_policy)
        )
        
        # Wait for role to be available
        time.sleep(10)
        
        return role_arn
    except Exception as e:
        print(f"Error creating IAM role: {e}")
        raise

def register_vector_bucket(vector_bucket_name):
    """Register an existing S3 bucket as a vector-enabled bucket"""
    max_retries = 3
    retry_delay = 5
    
    for attempt in range(max_retries):
        try:
            print(f"Registering bucket with S3 Vectors service (attempt {attempt + 1}/{max_retries})...")
            response = s3_vectors.create_vector_bucket(
                vectorBucketName=vector_bucket_name
            )
            print(f"Bucket registered with S3 Vectors service")
            return response
        except Exception as e:
            error_msg = str(e)
            if "AlreadyExists" in error_msg or "already exists" in error_msg.lower():
                print(f"Bucket already registered with S3 Vectors service")
                return None
            elif attempt < max_retries - 1:
                print(f"Registration attempt failed, waiting {retry_delay} seconds...")
                time.sleep(retry_delay)
                retry_delay *= 2
            else:
                print(f"Error registering bucket with S3 Vectors: {e}")
                raise

def create_vector_index(vector_bucket_name, index_name):
    """Create S3 vector index with non-filterable metadata to avoid S3 Vectors limits"""
    try:
        # Define metadata configuration with all keys as non-filterable to prevent hitting S3 Vectors limits
        # Bedrock automatically creates metadata keys during ingestion, marking them non-filterable
        # prevents exceeding the limit on filterable metadata fields
        metadata_configuration = {
            'nonFilterableMetadataKeys': [
                'AMAZON_BEDROCK_METADATA', # contains structured metadata
                'AMAZON_BEDROCK_TEXT', # contains chunk text content
                'x-amz-bedrock-kb-source-uri',
                'x-amz-bedrock-kb-data-source-id',
                'x-amz-bedrock-kb-chunk-id',
                'x-amz-bedrock-kb-document-id',
                'x-amz-bedrock-kb-document-page-number',
                'x-amz-bedrock-kb-document-chunk-id'
            ]
        }
        
        response = s3_vectors.create_index(
            vectorBucketName=vector_bucket_name,
            indexName=index_name,
            dataType='float32',
            dimension=1024,  # For titan-embed-text-v2
            distanceMetric='cosine',
            metadataConfiguration=metadata_configuration
        )
        
        index_arn = response['indexArn']
        print(f"Created S3 vector index with non-filterable metadata: {index_arn}")
        return index_arn
    except Exception as e:
        error_msg = str(e)
        if "ConflictException" in error_msg or "already exists" in error_msg.lower():
            # Index already exists, construct its ARN
            print(f"Index already exists, using existing index...")
            index_arn = f"arn:aws:s3vectors:{REGION}:{account_id}:bucket/{vector_bucket_name}/index/{index_name}"
            print(f"Using existing S3 vector index: {index_arn}")
            return index_arn
        else:
            print(f"Error creating vector index: {e}")
            raise

def create_knowledge_base(role_arn, vector_bucket_name, index_name, index_arn):
    """Create Bedrock Knowledge Base with S3 vector store and supplemental data storage for parsed outputs"""
    try:
        response = bedrock_agent.create_knowledge_base(
            name=KB_NAME,
            description=KB_DESCRIPTION,
            roleArn=role_arn,
            knowledgeBaseConfiguration={
                'type': 'VECTOR',
                'vectorKnowledgeBaseConfiguration': {
                    'embeddingModelArn': EMBEDDING_MODEL_ARN,
                    'supplementalDataStorageConfiguration': {
                        'storageLocations': [
                            {
                                'type': 'S3',
                                's3Location': {
                                    'uri': f"s3://{BUCKET_NAME}/"
                                }
                            }
                        ]
                    }
                }
            },
            storageConfiguration={
                'type': 'S3_VECTORS',
                's3VectorsConfiguration': {
                    'vectorBucketArn': f"arn:aws:s3vectors:{REGION}:{account_id}:bucket/{vector_bucket_name}",
                    'indexArn': index_arn
                }
            },
            tags=KB_TAGS
        )
        
        kb_id = response['knowledgeBase']['knowledgeBaseId']
        kb_arn = response['knowledgeBase']['knowledgeBaseArn']
        
        print(f"Created Knowledge Base:")
        print(f"  ID: {kb_id}")
        print(f"  ARN: {kb_arn}")
        
        return kb_id, kb_arn
    except Exception as e:
        error_msg = str(e)
        if "ConflictException" in error_msg or "already exists" in error_msg.lower():
            print(f"Knowledge Base already exists, retrieving existing KB...")
            kb_id = get_knowledge_base_id(KB_NAME)
            if kb_id:
                response = bedrock_agent.get_knowledge_base(knowledgeBaseId=kb_id)
                kb_arn = response['knowledgeBase']['knowledgeBaseArn']
                print(f"Using existing Knowledge Base:")
                print(f"  ID: {kb_id}")
                print(f"  ARN: {kb_arn}")
                return kb_id, kb_arn
            else:
                print(f"Error: KB exists but couldn't retrieve ID")
                raise
        else:
            print(f"Error creating knowledge base: {e}")
            raise

def create_data_source(kb_id, bucket_name, max_tokens=300, overlap_percentage=20):
    """Create data source for the knowledge base with custom chunking strategy and optional parser"""
    config = KB_CONFIGS[ACTIVE_KB_TYPE]
    parser_type = config['parser']
    
    try:
        # Build vector ingestion config
        vector_config = {
            'chunkingConfiguration': {
                'chunkingStrategy': 'SEMANTIC',
                'semanticChunkingConfiguration': {
                    'maxTokens': max_tokens,
                    'bufferSize': 1,
                    'breakpointPercentileThreshold': 95
                }
            }
        }
        
        # Add parser config if specified
        if parser_type == 'BEDROCK_DATA_AUTOMATION':
            vector_config['parsingConfiguration'] = {
                'parsingStrategy': 'BEDROCK_DATA_AUTOMATION',
                'bedrockDataAutomationConfiguration': {
                    'parsingModality': 'MULTIMODAL'
                }
            }
        
        response = bedrock_agent.create_data_source(
            knowledgeBaseId=kb_id,
            name=f"{KB_NAME}-data-source",
            description=f"S3 data source with {parser_type or 'default'} parser",
            dataSourceConfiguration={
                'type': 'S3',
                's3Configuration': {
                    'bucketArn': f"arn:aws:s3:::{bucket_name}",
                    'inclusionPrefixes': [config['documents_prefix']]
                }
            },
            vectorIngestionConfiguration=vector_config
        )
        
        data_source_id = response['dataSource']['dataSourceId']
        print(f"Created data source with {parser_type or 'default'} parser: {data_source_id}")
        
        return data_source_id
    except Exception as e:
        error_msg = str(e)
        if "ConflictException" in error_msg or "already exists" in error_msg.lower():
            print(f"Data source already exists, updating configuration...")
            data_source_id = get_data_source_id(kb_id)
            if data_source_id:
                # Update existing data source with new chunking and parsing configuration
                try:
                    # Rebuild vector config for update
                    vector_config = {
                        'chunkingConfiguration': {
                            'chunkingStrategy': 'SEMANTIC',
                            'semanticChunkingConfiguration': {
                                'maxTokens': max_tokens,
                                'bufferSize': 1,
                                'breakpointPercentileThreshold': 95
                            }
                        }
                    }
                    
                    if parser_type == 'BEDROCK_DATA_AUTOMATION':
                        vector_config['parsingConfiguration'] = {
                            'parsingStrategy': 'BEDROCK_DATA_AUTOMATION',
                            'bedrockDataAutomationConfiguration': {
                                'parsingModality': 'MULTIMODAL'
                            }
                        }
                    
                    bedrock_agent.update_data_source(
                        knowledgeBaseId=kb_id,
                        dataSourceId=data_source_id,
                        name=f"{KB_NAME}-data-source",
                        description=f"S3 data source with {parser_type or 'default'} parser",
                        dataSourceConfiguration={
                            'type': 'S3',
                            's3Configuration': {
                                'bucketArn': f"arn:aws:s3:::{bucket_name}",
                                'inclusionPrefixes': [config['documents_prefix']]
                            }
                        },
                        vectorIngestionConfiguration=vector_config
                    )
                    print(f"Updated data source with {parser_type or 'default'} parser: {data_source_id}")
                    return data_source_id
                except Exception as update_error:
                    print(f"Error updating data source: {update_error}")
                    raise
            else:
                print(f"Error: Data source exists but couldn't retrieve ID")
                raise
        else:
            print(f"Error creating data source: {e}")
            raise

def get_knowledge_base_id(kb_name=None):
    """Get knowledge base ID by name"""
    if kb_name is None:
        kb_name = KB_NAME
    
    try:
        response = bedrock_agent.list_knowledge_bases()
        for kb in response.get('knowledgeBaseSummaries', []):
            if kb['name'] == kb_name:
                return kb['knowledgeBaseId']
        return None
    except Exception as e:
        print(f"Error listing knowledge bases: {e}")
        return None

def get_data_source_id(kb_id):
    """Get data source ID for a knowledge base"""
    try:
        response = bedrock_agent.list_data_sources(knowledgeBaseId=kb_id)
        data_sources = response.get('dataSourceSummaries', [])
        if data_sources:
            return data_sources[0]['dataSourceId']
        return None
    except Exception as e:
        print(f"Error listing data sources: {e}")
        return None

def start_ingestion_job(kb_id, data_source_id):
    """Start an ingestion job to sync data from S3 to the knowledge base"""
    try:
        response = bedrock_agent.start_ingestion_job(
            knowledgeBaseId=kb_id,
            dataSourceId=data_source_id,
            description=f"Ingestion job started at {datetime.now().isoformat()}"
        )
        
        job_id = response['ingestionJob']['ingestionJobId']
        job_status = response['ingestionJob']['status']
        
        print(f"Started ingestion job: {job_id}")
        print(f"Status: {job_status}")
        
        return job_id
    except Exception as e:
        print(f"Error starting ingestion job: {e}")
        raise

def get_ingestion_job_status(kb_id, data_source_id, job_id):
    """Get the status of an ingestion job"""
    try:
        response = bedrock_agent.get_ingestion_job(
            knowledgeBaseId=kb_id,
            dataSourceId=data_source_id,
            ingestionJobId=job_id
        )
        
        job = response['ingestionJob']
        return {
            'status': job['status'],
            'startedAt': job.get('startedAt'),
            'updatedAt': job.get('updatedAt'),
            'statistics': job.get('statistics', {}),
            'failureReasons': job.get('failureReasons', [])
        }
    except Exception as e:
        print(f"Error getting ingestion job status: {e}")
        return None

def wait_for_ingestion_job(kb_id, data_source_id, job_id, max_wait_seconds=600):
    """Wait for an ingestion job to complete"""
    start_time = time.time()
    
    print(f"Waiting for ingestion job {job_id} to complete...")
    
    while time.time() - start_time < max_wait_seconds:
        status_info = get_ingestion_job_status(kb_id, data_source_id, job_id)
        
        if status_info is None:
            print("Failed to get job status")
            return False
        
        status = status_info['status']
        print(f"Current status: {status}")
        
        if status == 'COMPLETE':
            stats = status_info.get('statistics', {})
            print(f"Ingestion complete!")
            print(f"  Documents scanned: {stats.get('numberOfDocumentsScanned', 0)}")
            print(f"  Documents processed: {stats.get('numberOfDocumentsIndexed', 0)}")
            print(f"  Documents failed: {stats.get('numberOfDocumentsFailed', 0)}")
            
            # Display failure reasons if any documents failed
            failure_reasons = status_info.get('failureReasons', [])
            if failure_reasons:
                print(f"\n  Failure details:")
                for reason in failure_reasons:
                    print(f"    - {reason}")
            
            return True
        elif status == 'FAILED':
            print(f"Ingestion job failed!")
            return False
        
        time.sleep(10)
    
    print(f"Timeout waiting for ingestion job")
    return False

def sync_knowledge_base(kb_id=None, wait_for_completion=True):
    """Sync the knowledge base with latest S3 data"""
    try:
        # Get KB ID if not provided
        if kb_id is None:
            kb_id = get_knowledge_base_id()
            if kb_id is None:
                print(f"Knowledge base '{KB_NAME}' not found")
                return False
        
        print(f"Syncing knowledge base: {kb_id}")
        
        # Get data source ID
        data_source_id = get_data_source_id(kb_id)
        if data_source_id is None:
            print(f"No data source found for knowledge base {kb_id}")
            return False
        
        print(f"Data source ID: {data_source_id}")
        
        # Start ingestion job
        job_id = start_ingestion_job(kb_id, data_source_id)
        
        # Wait for completion if requested
        if wait_for_completion:
            success = wait_for_ingestion_job(kb_id, data_source_id, job_id)
            return success
        
        return True
        
    except Exception as e:
        print(f"Error syncing knowledge base: {e}")
        return False

def main():
    """Main function to create complete Bedrock Knowledge Base setup with S3 vector store"""
    try:
        print("Starting Bedrock Knowledge Base creation with S3 vector store...\n")
        
        # Step 1: Create S3 bucket for documents
        print("Step 1: Creating S3 bucket for documents...")
        bucket_name = create_s3_bucket()
        print()
        
        # Step 2: Create S3 bucket for vector store
        print("Step 2: Creating S3 bucket for vector store...")
        vector_bucket_name = f"{BUCKET_NAME}-vectors"
        try:
            if REGION == 'us-east-1':
                s3.create_bucket(Bucket=vector_bucket_name)
            else:
                s3.create_bucket(
                    Bucket=vector_bucket_name,
                    CreateBucketConfiguration={'LocationConstraint': REGION}
                )
            print(f"Created vector store bucket: {vector_bucket_name}")
        except s3.exceptions.BucketAlreadyOwnedByYou:
            print(f"Vector store bucket already exists: {vector_bucket_name}")
        except s3.exceptions.BucketAlreadyExists:
            print(f"Error: Bucket name {vector_bucket_name} already taken by another account")
            raise
        except Exception as e:
            print(f"Error creating vector store bucket: {e}")
            raise
        
        # Verify bucket exists and is accessible
        try:
            s3.head_bucket(Bucket=vector_bucket_name)
            bucket_location = s3.get_bucket_location(Bucket=vector_bucket_name)
            bucket_region = bucket_location['LocationConstraint'] or 'us-east-1'
            print(f"Verified vector bucket exists in region: {bucket_region}")
            
            if bucket_region != REGION:
                print(f"WARNING: Vector bucket is in {bucket_region} but script is configured for {REGION}")
                print(f"This may cause issues. Please ensure bucket and KB are in the same region.")
        except Exception as e:
            print(f"Error verifying bucket: {e}")
            raise
        print()
        
        # Step 3: Create IAM role
        print("Step 3: Creating IAM role with S3 vector store permissions...")
        role_arn = create_kb_role(vector_bucket_name)
        print()
        
        # Step 4: Register bucket with S3 Vectors service
        print("Step 4: Registering bucket with S3 Vectors service...")
        register_vector_bucket(vector_bucket_name)
        print()
        
        # Step 5: Create S3 vector index
        print("Step 5: Creating S3 vector index...")
        config = KB_CONFIGS[ACTIVE_KB_TYPE]
        index_name = f"{KB_NAME}-index-{config['index_suffix']}"
        index_arn = create_vector_index(vector_bucket_name, index_name)
        print()

        # Step 6: Create Knowledge Base with S3 vector store
        print("Step 6: Creating Knowledge Base with S3 vector store...")
        kb_id, kb_arn = create_knowledge_base(role_arn, vector_bucket_name, index_name, index_arn)
        print()

        # Step 7: Create data source
        print("Step 7: Creating data source...")
        data_source_id = create_data_source(kb_id, bucket_name)
        print()
        
        print("\nSetup complete!")
        print(f"\nResources created:")
        print(f"  - Data bucket: {bucket_name}")
        print(f"  - Vector store bucket: {vector_bucket_name}")
        print(f"  - Knowledge Base ID: {kb_id}")
        print(f"  - Data Source ID: {data_source_id}")
        config = KB_CONFIGS[ACTIVE_KB_TYPE]
        print(f"\nNext steps:")
        print(f"1. Upload documents to s3://{bucket_name}/{config['documents_prefix']}")
        print(f"2. Run: python {__file__} --sync --kb-type {ACTIVE_KB_TYPE}")
        print(f"   to ingest data into the knowledge base")
        
    except Exception as e:
        print(f"\nError during setup: {e}")
        raise



if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Create and manage AWS Bedrock Knowledge Base"
    )
    parser.add_argument(
        '--setup',
        action='store_true',
        help='Run initial setup (create KB, roles, buckets)'
    )
    parser.add_argument(
        '--sync',
        action='store_true',
        help='Sync data from S3 to knowledge base'
    )
    parser.add_argument(
        '--kb-type',
        choices=['default-md', 'automation-pdf'],
        default='default-md',
        help='Type of KB to create/sync (default-md: default parser + markdown, automation-pdf: Data Automation parser + PDF)'
    )
    parser.add_argument(
        '--kb-id',
        type=str,
        help='Knowledge base ID (for sync operations)'
    )
    parser.add_argument(
        '--no-wait',
        action='store_true',
        help='Start sync job without waiting for completion'
    )
    
    args = parser.parse_args()
    
    # Set active KB type from args
    ACTIVE_KB_TYPE = args.kb_type
    KB_NAME = KB_CONFIGS[ACTIVE_KB_TYPE]['name']
    KB_DESCRIPTION = KB_CONFIGS[ACTIVE_KB_TYPE]['description']
    
    # If no arguments provided, run setup by default
    if not args.setup and not args.sync:
        args.setup = True
    
    if args.setup:
        main()
    
    if args.sync:
        wait_for_completion = not args.no_wait
        success = sync_knowledge_base(kb_id=args.kb_id, wait_for_completion=wait_for_completion)
        if success:
            print("\n✓ Knowledge base sync completed successfully!")
        else:
            print("\n✗ Knowledge base sync failed")
            exit(1)



# # Create KB with default parser + markdown files
# python 00_create-bedrock-kb.py --setup --kb-type default-md

# # Create KB with Data Automation parser + PDF files
# python 00_create-bedrock-kb.py --setup --kb-type automation-pdf

# # Sync markdown KB after adding files to S3
# python 00_create-bedrock-kb.py --sync --kb-type default-md

# # Sync PDF KB
# python 00_create-bedrock-kb.py --sync --kb-type automation-pdf

# # Sync without waiting for completion
# python 00_create-bedrock-kb.py --sync --kb-type default-md --no-wait

"""
#### Corresponding AWS CLI syntax:
# Create S3 bucket for documents
aws s3 mb s3://my-kb-bucket --region us-east-1

# Create S3 bucket for vector store
aws s3 mb s3://my-kb-bucket-vectors --region us-east-1

# Create IAM role (save trust policy to trust-policy.json)
aws iam create-role \\
    --role-name bedrock-kb-role \\
    --assume-role-policy-document file://trust-policy.json

# Attach inline policy for S3 data source access
aws iam put-role-policy \\
    --role-name bedrock-kb-role \\
    --policy-name s3-data-access \\
    --policy-document file://s3-data-policy.json

# Attach inline policy for S3 vector store access
aws iam put-role-policy \\
    --role-name bedrock-kb-role \\
    --policy-name s3-vector-access \\
    --policy-document file://s3-vector-policy.json

# Attach inline policy for Bedrock model access
aws iam put-role-policy \\
    --role-name bedrock-kb-role \\
    --policy-name bedrock-model-access \\
    --policy-document file://bedrock-policy.json

# Create Knowledge Base with S3 vector store
aws bedrock-agent create-knowledge-base \\
    --name my-knowledge-base \\
    --description "My KB with S3 vector store" \\
    --role-arn arn:aws:iam::ACCOUNT_ID:role/bedrock-kb-role \\
    --knowledge-base-configuration type=VECTOR,vectorKnowledgeBaseConfiguration={embeddingModelArn=arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v1} \\
    --storage-configuration type=S3_VECTORS,s3VectorsConfiguration={vectorBucketArn=arn:aws:s3:::my-kb-bucket-vectors,indexName=my-kb-index}

# Create Data Source
aws bedrock-agent create-data-source \\
    --knowledge-base-id KB_ID \\
    --name my-data-source \\
    --data-source-configuration type=S3,s3Configuration={bucketArn=arn:aws:s3:::my-kb-bucket,inclusionPrefixes=[documents/]}

# Start ingestion job
aws bedrock-agent start-ingestion-job \\
    --knowledge-base-id KB_ID \\
    --data-source-id DS_ID

# Query the knowledge base
aws bedrock-agent-runtime retrieve-and-generate \\
    --input text="Your question here" \\
    --retrieve-and-generate-configuration type=KNOWLEDGE_BASE,knowledgeBaseConfiguration={knowledgeBaseId=KB_ID,modelArn=arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-v2}
"""