"""
Disclaimer: This script was generated by Claude Code (Claude Opus 4.5) based on the requirements
provided for programmatically testing functionality available in the "Test Knowledge Base" section of the console.

Allows you to:
1. Enter a prompt and see retrieved chunks (like the Test Playground)
2. See what metadata filters were applied (when using LLM-generated filters)
3. Compare filtered vs unfiltered retrieval
4. Get generated responses with source attribution
5. Generate responses with URL citations from metadata (--cite-urls)

Usage:
    python 03_test-bedrock-kb.py --query "What are the employment regulations?"
    python 03_test-bedrock-kb.py --query "..." --no-filter    # Disable metadata filtering
    python 03_test-bedrock-kb.py --query "..." --retrieve-only # Just retrieve, no generation
    python 03_test-bedrock-kb.py --query "..." --compare       # Compare filtered vs unfiltered
    python 03_test-bedrock-kb.py --query "..." --cite-urls    # Custom generation with URL citations
    python 03_test-bedrock-kb.py --interactive                 # Interactive mode
"""

import boto3
import json
import argparse
from typing import Optional

from config import (
    KB_CONFIGS,
    REGION,
    METADATA_SCHEMA_S3_URI,
    SYSTEM_PROMPT_PATH,
    GENERATION_MODEL_ARN,
    GENERATION_MODEL_ARN_LIGHT,
    FILTER_GENERATION_MODEL_ARN
)
from utils.kb_display import (
    INTERACTIVE_HELP,
    print_retrieval_results,
    print_generation_results,
    print_generation_with_urls_results,
    print_comparison_summary,
)


# ============================================================
# Config & Setup
# ============================================================

# Initialize boto3 clients shared across functions
bedrock_agent_runtime = boto3.client('bedrock-agent-runtime', region_name=REGION)  # KB retrieval & RAG
s3 = boto3.client('s3', region_name=REGION)

GENERATION_MODELS = {
    'normal': GENERATION_MODEL_ARN,
    'light': GENERATION_MODEL_ARN_LIGHT,
}

def load_metadata_schema() -> list:
    """Load metadata schema from S3 for implicit filtering"""
    try:
        # Parse S3 URI
        uri_parts = METADATA_SCHEMA_S3_URI.replace('s3://', '').split('/', 1)
        bucket = uri_parts[0]
        key = uri_parts[1]

        # Download schema
        response = s3.get_object(Bucket=bucket, Key=key)
        schema = json.loads(response['Body'].read().decode('utf-8'))

        return schema
    except Exception as e:
        print(f"Warning: Could not load metadata schema from {METADATA_SCHEMA_S3_URI}: {e}")
        print("Metadata filtering will be disabled.")
        return []


def load_system_prompt(file_path: str = None) -> Optional[str]:
    """Load system prompt from a markdown file.

    Args:
        file_path: Path to the system prompt .md file. If None, uses SYSTEM_PROMPT_PATH.

    Returns:
        The system prompt text, or None if file doesn't exist or can't be read.
    """
    path = file_path or SYSTEM_PROMPT_PATH
    try:
        with open(path, 'r', encoding='utf-8') as f:
            return f.read().strip()
    except FileNotFoundError:
        print(f"Info: System prompt file not found at {path}. Using no system prompt.")
        return None
    except Exception as e:
        print(f"Warning: Could not load system prompt from {path}: {e}")
        return None


# Load schema and system prompt at module initialization so they are accessible by all functions below
METADATA_SCHEMA = load_metadata_schema()
SYSTEM_PROMPT = load_system_prompt()


def build_retrieval_config(
    num_results: int = 5,
    use_metadata_filter: bool = True,
    manual_filter: Optional[dict] = None,
    metadata_schema: list = METADATA_SCHEMA,
    filter_model_id: str = FILTER_GENERATION_MODEL_ARN
) -> dict:
    """Build the shared retrievalConfiguration dict used by retrieve and retrieve_and_generate."""
    vector_search_config = {
        'numberOfResults': num_results,
    }

    if manual_filter:
        vector_search_config['filter'] = manual_filter
    elif use_metadata_filter and metadata_schema:
        vector_search_config['implicitFilterConfiguration'] = {
            'metadataAttributes': metadata_schema,
            'modelArn': filter_model_id
        }

    return {'vectorSearchConfiguration': vector_search_config}


# ============================================================
# KB Lookup
# ============================================================

def get_knowledge_base_id(kb_name: str, region: str = REGION) -> Optional[str]:
    """Get knowledge base ID by name using the Bedrock Agent control plane API."""
    try:
        bedrock_agent = boto3.client('bedrock-agent', region_name=region)
        response = bedrock_agent.list_knowledge_bases()
        for kb in response.get('knowledgeBaseSummaries', []):
            if kb['name'] == kb_name:
                return kb['knowledgeBaseId']
        return None
    except Exception as e:
        print(f"Error listing knowledge bases: {e}")
        return None


# ============================================================
# Core Retrieval Functions
# ============================================================

def retrieve_chunks(
    kb_id: str,
    query: str,
    use_metadata_filter: bool = True,
    num_results: int = 5,
    manual_filter: Optional[dict] = None
) -> dict:
    """
    Retrieve chunks from the knowledge base.

    Args:
        kb_id: Knowledge Base ID
        query: The query text
        use_metadata_filter: Whether to use LLM-generated metadata filtering
        num_results: Number of results to retrieve
        manual_filter: Optional manual filter to apply (overrides LLM generation)

    Returns:
        Dictionary with retrieval results and metadata
    """
    retrieval_config = build_retrieval_config(num_results, use_metadata_filter, manual_filter)

    filter_status = 'filtered' if (use_metadata_filter and not manual_filter) else (
        'manual_filter' if manual_filter else 'unfiltered'
    )

    try:
        # Retrieve API doc: https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_Retrieve.html
        response = bedrock_agent_runtime.retrieve(
            knowledgeBaseId=kb_id,
            retrievalQuery={'text': query},
            retrievalConfiguration=retrieval_config
        )
        # Botocore responses may not persist arbitrary keys, so wrap in a
        # plain dict that includes the filter status alongside the results.
        return {**response, 'filterStatus': filter_status}
    except bedrock_agent_runtime.exceptions.ValidationException as e:
        # The implicit filter may generate unsupported operators (e.g.
        # STRING_CONTAINS) for certain queries.  Fall back to unfiltered
        # vector search so the question still gets an answer.
        if use_metadata_filter and not manual_filter:
            print(f"Warning: implicit filter failed ({e}), retrying without metadata filter")
            fallback_config = {
                'vectorSearchConfiguration': {
                    'numberOfResults': num_results,
                }
            }
            response = bedrock_agent_runtime.retrieve(
                knowledgeBaseId=kb_id,
                retrievalQuery={'text': query},
                retrievalConfiguration=fallback_config
            )
            return {**response, 'filterStatus': 'fallback_unfiltered'}
        raise
    except Exception as e:
        print(f"Error during retrieval: {e}")
        raise


def retrieve_and_generate(
    kb_id: str,
    query: str,
    use_metadata_filter: bool = True,
    num_results: int = 5,
    manual_filter: Optional[dict] = None,
    generation_model_arn: str = GENERATION_MODEL_ARN_LIGHT
) -> dict:
    """
    Retrieve chunks and generate a response.

    Args:
        kb_id: Knowledge Base ID
        query: The query text
        use_metadata_filter: Whether to use LLM-generated metadata filtering
        num_results: Number of results to retrieve
        manual_filter: Optional manual filter to apply
        generation_model_arn: Model ARN for response generation

    Returns:
        Dictionary with generation results, citations, and retrieved chunks
    """
    retrieval_config = build_retrieval_config(num_results, use_metadata_filter, manual_filter)

    try:
        # Retrieve and Generate API doc: https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_RetrieveAndGenerate.html
        response = bedrock_agent_runtime.retrieve_and_generate(
            input={'text': query},
            retrieveAndGenerateConfiguration={
                'type': 'KNOWLEDGE_BASE',
                'knowledgeBaseConfiguration': {
                    'knowledgeBaseId': kb_id,
                    'modelArn': generation_model_arn,
                    'retrievalConfiguration': retrieval_config
                }
            }
        )
        return response
    except Exception as e:
        print(f"Error during retrieve and generate: {e}")
        raise


def retrieve_and_generate_with_urls(
    kb_id: str,
    query: str,
    use_metadata_filter: bool = True,
    num_results: int = 5,
    url_metadata_key: str = 'url',
    generation_model_arn: str = GENERATION_MODEL_ARN_LIGHT,
    skill: str = None
) -> dict:
    """
    Retrieve chunks, extract URLs from metadata, and generate response with citations.

    This uses a two-step process:
    1. Call retrieve() to get chunks with their metadata (including URLs)
    2. Build a custom prompt with URLs injected, then call the model directly

    This ensures the model sees the URLs and can cite them in its response.

    Args:
        kb_id: Knowledge Base ID
        query: The query text
        use_metadata_filter: Whether to use LLM-generated metadata filtering
        num_results: Number of results to retrieve
        url_metadata_key: The metadata key where URL is stored (default: 'url')
        generation_model_arn: Model ARN for response generation
        skill: Optional skill text (from agentic workflow). Overrides module-level
            SYSTEM_PROMPT when provided. Use this when calling from an orchestrator.

    Returns:
        Dictionary with generated response, sources, and retrieved chunks
    """
    # Step 1: Retrieve chunks (metadata including URL comes back)
    retrieval_response = retrieve_chunks(
        kb_id=kb_id,
        query=query,
        use_metadata_filter=use_metadata_filter,
        num_results=num_results
    )

    results = retrieval_response.get('retrievalResults', [])

    # Fallback: if filtering returned no results, retry without the filter
    if not results and use_metadata_filter:
        print("  No results with filter — retrying without metadata filter")
        retrieval_response = retrieve_chunks(
            kb_id=kb_id,
            query=query,
            use_metadata_filter=False,
            num_results=num_results
        )
        retrieval_response['filterStatus'] = 'fallback_no_results'
        results = retrieval_response.get('retrievalResults', [])

    if not results:
        return {
            'generated_text': "No relevant information found in the knowledge base.",
            'sources': [],
            'retrieval_response': retrieval_response,
            'filter_status': retrieval_response.get('filterStatus', 'unknown')
        }

    # Step 2: Build context string with URLs extracted from metadata
    context_parts = []
    sources = []

    for i, chunk in enumerate(results, 1):
        text = chunk.get('content', {}).get('text', '')
        metadata = chunk.get('metadata', {})

        # Extract URL from metadata (stored during ingestion via .metadata.json)
        url = metadata.get(url_metadata_key, None)

        # Fallback to S3 URI if no custom URL metadata
        if not url:
            s3_location = chunk.get('location', {}).get('s3Location', {})
            url = s3_location.get('uri', 'Unknown source')

        sources.append({
            'index': i,
            'url': url,
            'metadata': {k: v for k, v in metadata.items()
                        if not k.startswith('AMAZON_BEDROCK')},
            'score': chunk.get('score', 'N/A')
        })

        # Build metadata header so the generation model can use tags for
        # prioritization (document_type) and citation (name, source, year).
        meta_lines = [f"[Source {i}]", f"URL: {url}"]
        for key in ('document_name', 'document_type', 'source',
                     'publication_year'):
            value = metadata.get(key)
            if value:
                label = key.replace('_', ' ').title()
                meta_lines.append(f"{label}: {value}")

        context_parts.append("\n".join(meta_lines) + f"\n\n{text}")

    context = "\n\n---\n\n".join(context_parts)

    # Step 3: Build user prompt (context + question only)
    prompt = f"""Sources:
{context}

Question: {query}"""

    # Step 4: Call the model directly via Bedrock Runtime (not the KB agent runtime)
    try:
        # Bedrock Runtime API doc: https://docs.aws.amazon.com/bedrock/latest/APIReference/API_Operations_Amazon_Bedrock_Runtime.html
        bedrock_runtime = boto3.client('bedrock-runtime', region_name=REGION)
        # AWS Anthropic doc: https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-anthropic-claude-messages.html
        body_params = {
            'anthropic_version': 'bedrock-2023-05-31',
            'max_tokens': 2048,
            'messages': [{'role': 'user', 'content': prompt}]
        }

        # Agentic workflow: skill overrides the default system prompt
        effective_prompt = skill if skill is not None else SYSTEM_PROMPT
        if effective_prompt:
            body_params['system'] = effective_prompt
        # `invoke_model` doc: https://docs.aws.amazon.com/boto3/latest/reference/services/bedrock-runtime/client/invoke_model.html
        response = bedrock_runtime.invoke_model(
            modelId=generation_model_arn,
            body=json.dumps(body_params)
        )

        result = json.loads(response['body'].read())
        generated_text = result['content'][0]['text']

        return {
            'generated_text': generated_text,
            'sources': sources,
            'retrieval_response': retrieval_response,
            'filter_status': retrieval_response.get('filterStatus', 'unknown')
        }
    except Exception as e:
        print(f"Error during model invocation: {e}")
        raise


# ============================================================
# Interactive Mode & CLI
# ============================================================

def interactive_mode(kb_id: str, generation_model_arn: str = GENERATION_MODEL_ARN_LIGHT):
    """Interactive REPL for testing queries"""
    print(f"\n{'='*60}")
    print(" Interactive Knowledge Base Testing")
    print('='*60)
    print(INTERACTIVE_HELP)

    while True:
        try:
            user_input = input("Query> ").strip()

            if not user_input:
                continue

            if user_input.lower() == '/quit':
                print("Goodbye!")
                break

            if user_input.lower() == '/help':
                print(INTERACTIVE_HELP)
                continue

            if user_input.startswith('/retrieve-nofilter '):
                query = user_input[19:].strip()
                response = retrieve_chunks(kb_id, query, use_metadata_filter=False)
                print_retrieval_results(response)

            elif user_input.startswith('/retrieve '):
                query = user_input[10:].strip()
                response = retrieve_chunks(kb_id, query, use_metadata_filter=True)
                print_retrieval_results(response)

            elif user_input.startswith('/compare-generation '):
                query = user_input[20:].strip()
                print("⚠️  Note: /compare-generation makes 2 retrieval + 2 generation calls (highest cost)")
                # Generate both responses
                unfiltered_response = retrieve_and_generate(kb_id, query, use_metadata_filter=False, generation_model_arn=generation_model_arn)
                filtered_response = retrieve_and_generate(kb_id, query, use_metadata_filter=True, generation_model_arn=generation_model_arn)
                print("\n--- UNFILTERED Generation ---")
                print_generation_results(unfiltered_response)
                print("\n--- FILTERED Generation ---")
                print_generation_results(filtered_response)

            elif user_input.startswith('/compare '):
                query = user_input[9:].strip()
                print("⚠️  Note: /compare makes 2 retrieval calls (higher cost)")
                unfiltered = retrieve_chunks(kb_id, query, use_metadata_filter=False)
                filtered = retrieve_chunks(kb_id, query, use_metadata_filter=True)
                print_retrieval_results(unfiltered, "UNFILTERED Results")
                print_retrieval_results(filtered, "FILTERED Results")
                print_comparison_summary(unfiltered.get('retrievalResults', []),
                                         filtered.get('retrievalResults', []))

            elif user_input.startswith('/nofilter '):
                query = user_input[10:].strip()
                response = retrieve_and_generate(kb_id, query, use_metadata_filter=False, generation_model_arn=generation_model_arn)
                print_generation_results(response)

            elif user_input.startswith('/cite '):
                query = user_input[6:].strip()
                response = retrieve_and_generate_with_urls(kb_id, query, use_metadata_filter=True, generation_model_arn=generation_model_arn)
                print_generation_with_urls_results(response)

            else:
                # Default: retrieve and generate with filtering
                response = retrieve_and_generate(kb_id, user_input, use_metadata_filter=True, generation_model_arn=generation_model_arn)
                print_generation_results(response)

        except KeyboardInterrupt:
            print("\nGoodbye!")
            break
        except Exception as e:
            print(f"Error: {e}")


def main():
    parser = argparse.ArgumentParser(
        description="Test AWS Bedrock Knowledge Base retrieval and generation"
    )
    parser.add_argument(
        '--query', '-q',
        type=str,
        help='Query to send to the knowledge base'
    )
    parser.add_argument(
        '--kb-type',
        choices=['default-md', 'automation-pdf'],
        default='default-md',
        help='Type of KB to query (default: default-md)'
    )
    parser.add_argument(
        '--kb-id',
        type=str,
        help='Knowledge base ID (overrides --kb-type lookup)'
    )
    parser.add_argument(
        '--retrieve-only',
        action='store_true',
        help='Only retrieve chunks, do not generate response'
    )
    parser.add_argument(
        '--no-filter',
        action='store_true',
        help='Disable metadata filtering'
    )
    parser.add_argument(
        '--compare',
        action='store_true',
        help='Compare filtered vs unfiltered retrieval'
    )
    parser.add_argument(
        '--num-results', '-n',
        type=int,
        default=5,
        help='Number of chunks to retrieve (default: 5)'
    )
    parser.add_argument(
        '--cite-urls',
        action='store_true',
        help='Use custom generation that injects URLs from metadata into the prompt'
    )
    parser.add_argument(
        '--interactive', '-i',
        action='store_true',
        help='Run in interactive mode'
    )
    parser.add_argument(
        '--model',
        choices=['normal', 'light'],
        default='light',
        help=f'Select which generation model to use (default: light). normal = {GENERATION_MODEL_ARN}, light = {GENERATION_MODEL_ARN_LIGHT}'
    )

    args = parser.parse_args()

    # Resolve generation model ARN
    if args.model == 'normal':
        generation_model_arn = GENERATION_MODEL_ARN
    else:
        generation_model_arn = GENERATION_MODEL_ARN_LIGHT

    # Get KB ID
    if args.kb_id:
        kb_id = args.kb_id
    else:
        kb_name = KB_CONFIGS[args.kb_type]['name']
        print(f"Looking up Knowledge Base: {kb_name}")
        kb_id = get_knowledge_base_id(kb_name)
        if not kb_id:
            print(f"Error: Knowledge Base '{kb_name}' not found")
            return 1

    print(f"Using Knowledge Base ID: {kb_id}")
    print(f"Using generation model: {args.model} ({generation_model_arn})")

    # Interactive mode
    if args.interactive:
        interactive_mode(kb_id, generation_model_arn=generation_model_arn)
        return 0

    # Single query mode
    if not args.query:
        print("Error: --query is required (or use --interactive)")
        return 1

    use_filter = not args.no_filter

    try:
        if args.compare:
            # --compare always runs both filtered and unfiltered (ignores --no-filter)
            unfiltered = retrieve_chunks(kb_id, args.query, use_metadata_filter=False, num_results=args.num_results)
            filtered = retrieve_chunks(kb_id, args.query, use_metadata_filter=True, num_results=args.num_results)
            print_retrieval_results(unfiltered, "UNFILTERED Results")
            print_retrieval_results(filtered, "FILTERED Results")
            print_comparison_summary(unfiltered.get('retrievalResults', []),
                                     filtered.get('retrievalResults', []))
        elif args.retrieve_only:
            response = retrieve_chunks(kb_id, args.query, use_filter, args.num_results)
            print_retrieval_results(response)
        elif args.cite_urls:
            response = retrieve_and_generate_with_urls(
                kb_id, args.query, use_filter, args.num_results
            )
            print_generation_with_urls_results(response)
        else:
            response = retrieve_and_generate(kb_id, args.query, use_filter, args.num_results)
            print_generation_results(response)
    except Exception as e:
        print(f"Error: {e}")
        if args.kb_id:
            print(f"If '--kb-id {kb_id}' is incorrect, try omitting it to look up the KB by name instead.")
        return 1

    return 0


if __name__ == "__main__":
    exit(main())